import { LOCALES } from './locales';

export const messages = {
  [LOCALES.ENGLISH]: {
    nav_casino: 'Top Online Casino',
    nav_sport: 'Top bets on sports',
    nav_faq: 'F.A.Q.',
    title_casino: 'Top Online Casinos in 2023',
    title_sport: 'Top sports betting',
    description_casino:
      'TOP online casino. TOP online sports betting. Play only at licensed casinos. All our casinos and sports betting are 100% safe and time-tested. When registering, you will receive the top bonuses. The best cashbacks up to 10%. Always up to date links. Fast payouts. Always ready to help you in our telegram channel. all our casinos for the first deposit from 100% + FS. When registering additionally using our promotional code, you will receive an additional bonus.',
    description_sport:
      'TOP online sports betting. All our partners are 100% safe and time-tested. High odds. The best bookmakers. Always up-to-date bonuses and links. Always ready to help you in our telegram channel.',
    link_bonus: 'Pick up bonus',
    footer_text:
      'Win to time information resource does not conduct games for real and/or virtual money, also, the site does not accept in any form the payment of rates and / other payments that are/may be associated with gambling, bookmakers or sweepstakes. Any materials on the Win to time information resource are published exclusively in information purposes. Participation in gambling can cause gambling addiction. Follow the rules (principles) of responsible gambling. At the first sign of addiction, immediately contact a specialist. Remember that gambling cannot be a source of income or an alternative job.',
    contacts: 'Our contacts:',
    telegram_title: 'Our Telegram',
    facebook_title: 'Our Facebook',
    instagram_title: 'Our Instagram',
    mail_title: 'Our mail',
    page_not_found: 'Page not found',
    content_faq: 'Content',
    content_li_1: 'Best Online Casinos',
    content_li_2: 'What payment methods do the best online casinos offer?',
    content_li_3: '7 important criteria for ranking the best online casinos',
    best_cas:
      'Since gambling activity in many countries of the world has been moved to dedicated zones, completely or partially banned, the online gambling industry has been actively developing. Online casinos have millions of fans. But even experienced players are not always well versed in choosing a virtual institution, hundreds of which have been opened over the past 10-15 years. The more the site provides opportunities for replenishment of the account, the better. After all, the financial part of the issue in gambling for money is of paramount importance. Free play is the best way to "learn" how your favorite slot machine or board game works. Without payment, it is impossible to play only card games, some lotteries and live dealer roulette.',
    pay_cas: 'Usually bookmakers offer the following ways to deposit and withdraw winnings:',
    pay_cas_li_1: 'bank cards;',
    pay_cas_li_2: 'electronic wallets;',
    pay_cas_li_3: 'cryptocurrency wallets;',
    pay_cas_li_4: 'payment terminals;',
    pay_cas_li_5: 'accounts of mobile operators.',
    pay_text:
      'The first two methods are the main ones and are present in almost all offices. The exact list of available payment methods depends on your geographic location. Some methods can work only in one direction: only for replenishment, but not for withdrawal - or vice versa. The speed of processing applications depends on the payment system. When replenishing a deposit, funds are usually credited to the account instantly. Withdrawal of winnings can take from several hours to several days. Most payment systems charge fees for their services, and the bookmaker cannot influence the amount of these payments. You can specify the amount of commissions on the website or in the support service of the payment system. Bookmakers themselves also have the right to charge fees for money transactions - but some platforms have abandoned this practice. Each payment method has minimum and maximum limits for deposits and withdrawals. To withdraw large winnings, cryptocurrencies are usually optimal - they either have no maximum limits at all, or they significantly exceed the limits of other payment systems.',
    rait_cas_li_1: '1. How to choose an honest online casino',
    rait_cas_li_1_t:
      'We have identified for you important criteria that you should definitely consider when choosing a virtual casino for playing for money. Taking into account these factors is your real protection against scammers in the gambling industry.',
    rait_cas_li_2: '2. Casino license',
    rait_cas_li_2_t:
      'No bonus programs and profitable promotions matter when a user comes to a casino that does not have a license. Only this document allows you to carry out gaming activities. Licensing is carried out by the gambling regulator or directly by the government of the country in whose jurisdiction the establishment is registered. Trusted world-famous operators undergo such a procedure in the Isle of Man, Curacao, Alderney and some others, they may have permission issued by regulators in Malta or in the UK. There is no need for a licensed establishment to hide licensing information. The document number and other data are usually indicated directly on the sites at the bottom of the page. To check the authenticity of the information, just go to the web resource of the licensing authority and check the validity of the license by number. For a player, having a license is a legal protection. If for some reason you have a conflict with the institution (you will be denied the payment of a large win, for example, without real reason), you can contact the authorities that oversee gambling activities. And your situation will be reviewed by independent arbitrators within 3 weeks. There is no license - there are no guarantees of fair payments, no protection. Your account can be unreasonably blocked, and the gaming story will end there, and the dishonest operator will simply appropriate the money. Unlicensed establishments often “sin” by using twisted non-certified slots, they can falsify the results of the tournament and not only. It is almost impossible to force him to pay the money fairly afterwards - there are no sufficient legal instruments for the successful conduct of the case. Availability Make sure the online casino accepts players from your country. The list of banned countries is usually present on the site. If the institution does not accept resident gamblers from your country, you may later have difficulties with verification and withdrawal of winnings.',
    rait_cas_li_3: '3. Customer service',
    rait_cas_li_3_t:
      'For any average player, from time to time there is a need to communicate with representatives of the support service to solve a particular problem. Check in advance that your institution has no problems receiving feedback. Before registering, make sure that the site has an online chat in which the operators really answer in the language of your everyday communication. The ideal option is to have several options for contacts. Let it be not only a live chat, but also an email address, and a phone number or Skype chat. Check in advance whether technical support works around the clock or answers customers only during the daytime. In the latter case, if you play at night, not a single problem can be solved quickly.',
    rait_cas_li_4: '4. Deposit and withdrawal options',
    rait_cas_li_4_t:
      'The more the site provides opportunities for replenishment of the account, the better. After all, the financial part of the issue in gambling for money is of paramount importance. Make sure that the casino provides withdrawal methods that suit you: bank cards, electronic wallets, various payment systems. Specify in advance: how quickly the funds are credited to the account, and whether there is a commission for depositing money; whether the casino requires that you wager your own deposit at least once (adequate establishments do not impose such requirements on their customers); in what currency you can replenish your account and play; how quickly withdrawal requests are processed, whether there are additional restrictions on the payment of own funds to players who, for example, take part in the bonus program; are there any limits (maximum and minimum) for withdrawing funds per day, week, month, etc. You should be alerted by the fact of excessively long processing of applications declared by the administration. For example, if the rules state that funds are withdrawn within 5-7 days, this is a long time. If the institution reserves the right to pay out large winnings in parts, it is also not worth contacting it. If applications are processed within a day - everything is fine!',
    rait_cas_li_5: '5. How does reputation affect the choice of an online casino?',
    rait_cas_li_5_t:
      'In the modern world, where access to any information is as accessible as possible, reputation plays almost a paramount role. This is the factor that an unscrupulous gambling establishment cannot influence. You can lure new players with hundreds of bonus programs with unimaginable generosity, but if the brand is “crushed” online by hundreds of negative reviews and complaints, you won’t be able to fight it. Reputational score is much more important than advertising. Studying reviews and other ratings is the best way to find a responsible and reliable operator. Independent ratings do not take into account the data published by the gambling clubs themselves. Third party online reviews help shape public opinion. And it is definitely worth relying on for a gambler.',
    rait_cas_li_6: '6. Is it possible to make money in an online casino?',
    rait_cas_li_6_t:
      'You should not take the casino as a place of work. In the classical sense, it is impossible to earn money here: no one can guarantee that, by constantly playing, a person can count on a stable income. Of course, if you are not a professional poker player. The situation is different there: competent strategies allow experienced players to win with enviable constancy. The average person should realize that no tactics and strategies are a 100% guarantee of winning. True, there are several recommendations that, although they will not allow you to become dollar millionaires, will help you not to thoughtlessly place bets in the first slot that comes across: Look for only proven, honest gambling establishments with a good rating and a spotless reputation to play. Choose from the list of slots those where there is the possibility of obtaining more or less large winnings. Such information will certainly be found on the site in the table with payments. Don\'t stop at one casino. If you win too often, the support service will certainly pay attention to you. Nevertheless, gambling clubs do not work in order to “get rich” for you - they are interested in earning money themselves. Take advantage of bonus offers. But only those where adequate wagering conditions apply. The average wager should not be more than x30 - x35. If you lose, do not seek to "return" the lost immediately. You can not play on emotions - only with a "cold" head. Pay attention to popular slots. This category includes slot machines that have been played most often. The more the slot is "charged" with the money of other players, the higher the probability of returning a big win.',
    rait_cas_li_7: '7. Is it possible to beat the casino and how to do it',
    rait_cas_li_7_t:
      'One should understand the work of probability theory. Each slot has its own “return” indicator. For verified providers, this figure is about 93-97%. What does it mean? 93% of the money invested in the machine is returned to the players as winnings. The remaining amount is the net income of the gambling establishment. Remember a few criteria: If previous users have lost enough funds, the probability of winning is significantly increased. The more money you invest in the game, the higher the chance of winning. It is impossible to hit a big jackpot by playing at the minimum bet. It is better to play on proven slots with a high payout percentage. It makes no sense to sit down at the machine, in which this figure is 70-75%. New slots often provide an opportunity to win. This is how software providers attract the attention of visitors. If the "new" appeared on the site just the other day, it\'s definitely worth a try. It is important to understand that each game in the institution has its own settings and functions according to a certain scheme. It is the understanding of this scheme that allows competent clients to take big winnings. But, of course, you should change casinos from time to time so that you are not interested in the JV and do not cut down on betting opportunities.',
    sport_li_1: 'Best bookmaker for online betting',
    sport_li_2: 'What payment methods do the best bookmakers offer?',
    sport_li_3: '5 important criteria for ranking the best bookmakers',
    the_best_online: 'The best bookmaker for online betting',
    the_best_online_t:
      "Online betting is becoming more and more popular every year. Owners of almost any models of computers, smartphones or tablets can register on the bookmaker's website and start betting. To do this, it is enough to be of legal age and have a stable Internet connection. Almost all bookmakers offer a wide range of sports bets. However, this does not mean that all providers are equally suitable for sports betting. Therefore, we present reviews of providers that have earned the trust of their customers over the years. Ambitious beginners will be able to find their bookmaker on our list. One thing can be said for sure: each provider must meet high quality standards in order to be included in the category Bookmaker of the Month. In other words: these bookmakers can be trusted!",
    sport_pay: 'What payment methods do the best bookmakers offer?',
    sport_pay_t: 'Usually bookmakers offer the following ways to deposit and withdraw winnings:',
    sport_pay_li_1: 'bank cards;',
    sport_pay_li_2: 'electronic wallets;',
    sport_pay_li_3: 'cryptocurrency wallets;',
    sport_pay_li_4: 'payment terminals;',
    sport_pay_li_5: 'accounts of mobile operators.',
    sport_pay_text:
      'The first two methods are the main ones and are present in almost all offices. The exact list of available payment methods depends on your geographic location. Some methods can work only in one direction: only for replenishment, but not for withdrawal - or vice versa. The speed of processing applications depends on the payment system. When replenishing a deposit, funds are usually credited to the account instantly. Withdrawal of winnings can take from several hours to several days. Most payment systems charge fees for their services, and the bookmaker cannot influence the amount of these payments. You can specify the amount of commissions on the website or in the support service of the payment system. Bookmakers themselves also have the right to charge fees for money transactions - but some platforms have abandoned this practice. Each payment method has minimum and maximum limits for deposits and withdrawals. To withdraw large winnings, cryptocurrencies are usually optimal - they either have no maximum limits at all, or they significantly exceed the limits of other payment systems.',
    sport_import_criteria: '5 important criteria for ranking the best bookmakers',
    sport_import_criteria_li_1: '1. Customer service',
    sport_import_criteria_li_1_t:
      "It is important that the bookmaker's support communicates in Russian or another language that you are fluent in. Most browsers today have built-in automatic translators - but they should not be trusted 100%, as they do not always cope with the specific betting terminology. Support should be available around the clock and through several channels: live chat, phone, email, instant messengers. An additional way to contact the BC is the official accounts of the project in social networks. The quality of the support service is an important indicator of the quality of the office as a whole. Experienced bettors, even before creating an account in a new bookmaker, ask questions to support staff in order to assess how quickly and competently they respond.",
    sport_import_criteria_li_2: '2. Security of your account',
    sport_import_criteria_li_2_t:
      'All noteworthy bookmakers offer two-factor authentication (2FA). This means that entering a username and password is not enough to enter your account. You will receive an additional code by e-mail or phone, which you will need to enter on the BC website. In recent years, bookmakers have appeared on the market, whose websites work on the blockchain. This reduces the likelihood of fraud to zero, since the system records information about all the actions taken: from accepting bets to announcing the results of the match, from accruing a bonus to completing an application for withdrawing funds. It is impossible to remove this information from the blockchain or quietly overwrite it.',
    sport_import_criteria_li_3: '3. Payments: How to withdraw funds to your details?',
    sport_import_criteria_li_3_t:
      'Withdrawal rules depend not only on the bookmaker, but also on the payment system. Almost all systems charge commissions for financial transactions, so you should clarify in advance what percentage you will be charged. It is more profitable to focus on such bookmakers that do not add additional commissions to these deductions on their part.',
    sport_import_criteria_li_4: '4. License',
    sport_import_criteria_li_4_t:
      'Having a license is a fundamental criterion when choosing a bookmaker. The fact that the bookmaker has this document is a guarantee that: Your personal information will be kept strictly confidential. No third parties will under any circumstances have access to them. Rewards will be paid promptly and fairly. The bookmaker will not cheat, change odds or apply hidden fees. The license number and the name of the organization that issued it are usually placed either in the footer on the main page or in the “About Us” section. If you do not see this information on the site, contact technical support. Then go to the website of the organization that issued the bookmaker a license and make sure that the office is really mentioned there.',
    sport_import_criteria_li_5: '5. Bonuses',
    sport_import_criteria_li_5_t:
      'It should also be noted here that when choosing a bookmaker, you should not focus on the number and variety of bonuses. The main thing in all incentive promotions is how appropriate they are. Calculate in advance whether the benefit received from the bonus will exceed the costs that will have to be incurred in order to receive it? Does the wager suit you? Will you meet the time allotted to use the bonus? The office will try to influence your emotions - but you must think pragmatically.',
  },

  [LOCALES.RUSSIAN]: {
    nav_casino: 'Топ онлайн казино',
    nav_sport: 'Топ ставки на спорт',
    nav_faq: 'F.A.Q.',
    title_casino: 'Топ онлайн казино в 2023 году',
    title_sport: 'Топ ставки на спорт',
    description_casino:
      'ТОП онлайн казино. ТОП онлайн ставки на спорт. Играй только в лицензированных казино. Все наши казино и ставки на спорт 100% безопасны и проверены временем. При регистрации вы получите самые топовые бонусы. Лучшие кешбеки до 10%. Всегда актуальные ссылки. Быстрые выплати. Всегда готовы вам помочь в нашем телеграм канале.  всех наших казино на первый депозит от 100% + FS. При регистрации дополнительно по нашему промкоду вы получите дополнительный бонус.',
    description_sport:
      'ТОП онлайн ставки на спорт. Все наши партнеры 100% безопасны и проверенны временем. Высокие коэффициенты. Лучшие букмекерские конторы. Всегда актуальные бонусы и ссылки. Всегда готовы вам помочь в нашем телеграм канале.',
    link_bonus: 'Забрать бонус',
    footer_text:
      'Информационный ресурс Win to time не проводит игры на реальные и/или виртуальные деньги, также сайт не принимает ни в какой форме оплату ставок и/иных платежей, которые связаны/могут быть связаны с азартными играми, букмекерами или тотализаторами. Любые материалы на информационном ресурсе Win to time публикуются исключительно в информационных целях. Участие в азартных играх может вызвать игровую зависимость. Соблюдайте правила (принципы) ответственной игры. При появлении первых признаков зависимости незамедлительно обратитесь к специалисту. Помните, что участие в азартных играх не может быть источником доходов или альтернативой работе.',
    contacts: 'Наши контакты:',
    telegram_title: 'Наш Телеграм',
    facebook_title: 'Наш Facebook',
    instagram_title: 'Наш Instagram',
    mail_title: 'Наша почта',
    page_not_found: 'Страница не найдена',
    content_faq: 'Содержание',
    content_li_1: 'Лучшие онлайн-казино',
    content_li_2: 'Какие способы оплаты предлагают лучшие онлайн казино',
    content_li_3: '7 важных критериев для рейтинга лучших онлайн казино',
    best_cas:
      'С тех пор как игорная деятельность во многих странах мира была перенесена ввыделенные зоны, полностью или частично запрещена, индустрия онлайн-гэмблинга стала активно развиваться. У интернет-казино появились миллионы поклонников. Но даже опытные игроки далеко не всегда хорошо ориентируются в выборе виртуального заведения, сотни которых были открыты за последние 10-15 лет. Чем больше сайт предоставляет возможностей для пополнения счета, тем лучше. Ведь финансовая часть вопроса в азартных играх на деньги имеет первостепенное значение. Бесплатная игра – лучший способ «изучить» работу понравившегося игрового автомата или настольной игры. Без оплаты невозможно играть только в карточные игры, некоторые лотереи и рулетку с живыми дилерами.',
    pay_cas:
      'Обычно букмекеры предлагают на выбор следующие способы пополнения счета и выведения выигранных средств:',
    pay_cas_li_1: 'банковские карты;',
    pay_cas_li_2: 'электронные кошельки;',
    pay_cas_li_3: 'криптовалютные кошельки;',
    pay_cas_li_4: 'платежные терминалы;',
    pay_cas_li_5: 'счета мобильных операторов.',
    pay_text:
      'Первые два способа являются основными и присутствуют практически во всех конторах. Точный список доступных методов платежа зависит от Вашего географического положения. Некоторые способы могут работать только в одну сторону: только на пополнение, но не на вывод — или наоборот. Скорость обработки заявок зависит от платежной системы. При пополнении депозита средства обычно поступают на счет мгновенно. Вывод выигрышей может занять от нескольких часов до нескольких суток. Большинство платежных систем взимают комиссии за свои услуги, и букмекер не может повлиять на объем этих выплат. Уточнить размер комиссий можно на сайте либо в службе поддержки платежной системы. Сами букмекерские конторы тоже имеют право взимать комиссии за денежные транзакции — но некоторые платформы отказались от такой практики. У каждого способа оплаты есть минимальные и максимальные лимиты на ввод и вывод средств. Для выведения крупных выигрышей обычно оптимальны криптовалюты — у них либо совсем отсутствуют максимальные лимиты, либо они значительно превышают лимиты прочих платежных систем.',
    rait_cas_li_1: '1. Как выбрать честное онлайн казино',
    rait_cas_li_1_t:
      'Мы выделили для вас важные критерии, которые непременно следует учитывать в своем выборе виртуального казино для игры на деньги. Учет перечисленных факторов – ваша реальная защита от мошенников в гэмблинг-индустрии.',
    rait_cas_li_2: '2. Лицензия казино',
    rait_cas_li_2_t:
      'Никакие бонусные программы и выгодные акции не имеют значения, когда пользователь приходит в казино, у которого отсутствует лицензия. Только этот документ позволяет осуществлять игровую деятельность. Осуществляется лицензирование игорным регулятором или непосредственно правительством страны, в юрисдикции которой зарегистрировано заведение. Проверенные операторы с мировым именем проходят такую процедуру на островах Мэн, Кюрасао, Олдерни и некоторых других, могут иметь разрешение, выданное регуляторами на Мальте или в Великобритании. Лицензированному заведению нет необходимости скрывать информацию о лицензировании. Номер документа и другие его данные обычно указываются непосредственно на сайтах в нижней части страницы. Чтобы проверить подлинность информации, достаточно зайти на веб-ресурс лицензирующего органа и проверить актуальность лицензии по номеру. Для игрока наличие лицензии – это юридическая защита. Если по каким-то причинам у вас возникнет конфликт с заведением (вам откажут в выплате крупного выигрыша, к примеру, без реальных на то оснований), вы сможете обратиться в органы, осуществляющие надзор за азартной деятельностью. И ваша ситуация будет рассмотрена независимыми арбитрами в течение 3 недель. Нет лицензии – нет ни гарантий честных выплат, ни защиты. Ваш аккаунт смогут безосновательно заблокировать, и на этом игровая история закончится, а деньги нечестный оператор просто присвоит себе. Нелицензированные заведения нередко «грешат» использованием подкрученных несертифицированных слотов, могут подтасовать результаты турнира и не только. Заставить его впоследствии справедливо выплатить деньги практически невозможно – нет достаточных юридических инструментов для успешного ведения дела. Доступность Убедитесь, что онлайн-казино принимает игроков из вашей страны. Список запрещенных стран обычно присутствует на сайте. Если гэмблеров-резидентов из вашей страны заведение не принимает, у вас могут впоследствии возникнуть трудности с прохождением верификации и выводом выигрышей.',
    rait_cas_li_3: '3. Служба поддержки клиентов',
    rait_cas_li_3_t:
      'У любого среднестатистического игрока время от времени появляется необходимость в общении с представителями службы поддержки для решения той или иной проблемы. Заранее проверьте, что в вашем заведении нет проблем с получением обратной связи. Перед регистрацией убедитесь, что на сайте имеется онлайн-чат, в котором операторы действительно отвечают на языке вашего повседневного общения. Идеальный вариант – наличие нескольких вариантов контактов. Пусть это будет не только живой чат, но и адрес электронной почты, и номер телефона или скайп-чат. Уточните заранее, работает ли техподдержка круглосуточно или отвечает клиентам только в дневное время. В последнем случае, если вы будете играть ночью, ни одну проблему решить оперативно просто не получится.',
    rait_cas_li_4: '4. Варианты ввода и вывода средств',
    rait_cas_li_4_t:
      'Чем больше сайт предоставляет возможностей для пополнения счета, тем лучше. Ведь финансовая часть вопроса в азартных играх на деньги имеет первостепенное значение. Убедитесь, что в казино предусмотрены способы вывода, которые вам подходят: банковские карты, электронные кошельки, всевозможные платежные системы. Заранее уточните: насколько быстро средства поступают на счет, и нет ли комиссии за ввод денег; требует ли казино обязательно отыграть собственный депозит хотя бы один раз (адекватные заведения подобные требования к своим клиентам не предъявляют); в какой валюте можно пополнять счет и играть; насколько быстро обрабатываются заявки на вывод, нет ли дополнительных ограничений по выплате собственных средств игрокам, которые, к примеру, принимают участие в бонусной программе; есть ли лимиты (максимальные и минимальные) на вывод средств в сутки, неделю, месяц и т.д. Вас должен насторожить заявленный администрацией факт чрезмерно долгой обработки заявок. К примеру, если в правилах прописано, что средства выводятся в течение 5-7 суток – это долго. Если заведение оставляет за собой право выплачивать крупные выигрыши частями, также связываться с ним не стоит. Если заявки обрабатываются в течение суток – все отлично!',
    rait_cas_li_5: '5. Как репутация влияет на выбор интернет-казино?',
    rait_cas_li_5_t:
      'В современном мире, где доступ к любой информации максимально доступен, репутация играет чуть ли не первостепенную роль. Это тот фактор, на который не может повлиять недобросовестное игорное заведение. Можно заманивать новых игроков сотнями бонусных программ с невообразимой щедростью, но если в сети бренд «раздавлен» сотнями негативных отзывов и жалоб, с этим бороться не получится. Репутационная оценка гораздо важнее рекламы. Изучение отзывов и других рейтинговых оценок – лучший способ найти ответственного и надежного оператора. Независимые рейтинги мало учитывают данные, которые публикуются самими игорными клубами. Сторонние интернет-обзоры помогают формировать общественное мнение. И на него точно стоит опираться гэмблеру.',
    rait_cas_li_6: '6. Можно ли заработать в интернет-казино?',
    rait_cas_li_6_t:
      'Не следует воспринимать казино как место работы. В классическом понимании заработок здесь получить невозможно: никто не даст гарантии, что, постоянно играя, человек может рассчитывать на стабильный доход. Конечно, если вы не профессиональный игрок в покер. Там дело обстоит иначе: грамотные стратегии позволяют опытным игрокам выигрывать с завидным постоянством. Обывателю же следует осознать, что никакие тактики и стратегии – не 100% гарантия выигрыша. Правда, есть несколько рекомендаций, которые хоть и не позволят стать долларовыми миллионерами, но помогут не бездумно делать ставки в первом попавшемся слоте: Ищите для игры только проверенные, честные игорные заведения с хорошим рейтингом и незапятнанной репутацией. Выбирайте в списке слотов те, где есть возможность получения более или менее крупных выигрышей. Такая информация непременно найдется на сайте в таблице с выплатами. Не останавливайтесь на одном казино. Если вы слишком часто будете выигрывать, служба поддержки непременно обратит на вас внимание. Все же игорные клубы работают не для того, чтобы вас «озолотить» – они заинтересованы зарабатывать сами. Пользуйтесь бонусными предложениями. Но только теми, где действуют адекватные условия отыгрыша. Средний вейджер не должен составлять более х30 – х35. Если проиграли, не стремитесь тут же «вернуть» утраченное. Нельзя играть на эмоциях – только с «холодной» головой. Обращайте внимание на популярные слоты. В эту категорию попадают автоматы, в которые играли чаще всего. Чем больше слот «заряжен» деньгами других игроков, тем выше вероятность отдачи крупного выигрыша.',
    rait_cas_li_7: '7. Можно ли обыграть казино и каким образом это сделать',
    rait_cas_li_7_t:
      'Следует понимать работу теории вероятности. У каждого слота есть свой показатель «отдачи». У проверенных провайдеров эта цифра составляет порядка 93-97%. Что это значит? 93% вложенных в автомат денег возвращается игрокам в качестве выигрышей. Оставшаяся сумма – чистый доход игорного заведения. Запомните несколько критериев: Если предыдущие пользователи проиграли достаточно средств, вероятность получения выигрыша существенно увеличивается. Чем больше средств вы вкладываете в игру, тем выше шанс выйти победителем. Невозможно сорвать крупный куш, играя по минимальной ставке. Играть лучше на проверенных слотах с высоким процентом выдачи. Нет смысла садиться за автомат, у которого этот показатель составляет 70-75%. Новые слоты нередко дают возможность победить. Так провайдеры софта привлекают внимание посетителей. Если «новинка» появилась на сайте буквально на днях, пробовать точно стоит. Важно понимать, что каждая игра в заведении имеет свои установленные настройки и функционирует по определенной схеме. Именно понимание этой схемы позволяет грамотным клиентам забирать крупные выигрыши. Но, конечно, следует менять казино время от времени, чтобы вами не заинтересовались в СП и не урезали возможности совершения ставок.',
    sport_li_1: 'Лучший букмекер для размещения ставок в Интернете',
    sport_li_2: 'Какие способы оплаты предлагают лучшие букмекеры?',
    sport_li_3: '5 важных критериев для рейтинга лучших букмекерских контор',
    the_best_online: 'Лучший букмекер для размещения ставок в Интернете',
    the_best_online_t:
      'Онлайн-беттинг с каждым годом становится все популярнее. Обладатели практически любых моделей компьютеров, смартфонов или планшетов могут зарегистрироваться на сайте букмекерской конторы и начать делать ставки. Для этого достаточно быть совершеннолетним и располагать стабильным подключением к интернету. Почти все букмекеры предлагают широкий выбор спортивных ставок. Однако это не означает, что все провайдеры одинако подходят для размещения спортивных ставок. Поэтому мы представляем обзоры провайдеров, которые заработали доверие своих клиентов на протяжении многих лет. Амбициозные новички смогут найти своего букмекера в нашем списке. Можно сказать точно одно: каждый провайдер для того, чтобы попасть в категорию «Букмекерская контора месяца», должен соответствовать высоким стандартам качества. Другими словами: этим букмекерам можно доверять!',
    sport_pay: 'Какие способы оплаты предлагают лучшие букмекеры?',
    sport_pay_t:
      'Обычно букмекеры предлагают на выбор следующие способы пополнения счета и выведения выигранных средств:',
    sport_pay_li_1: 'банковские карты;',
    sport_pay_li_2: 'электронные кошельки;',
    sport_pay_li_3: 'криптовалютные кошельки;',
    sport_pay_li_4: 'платежные терминалы;',
    sport_pay_li_5: 'счета мобильных операторов.',
    sport_pay_text:
      'Первые два способа являются основными и присутствуют практически во всех конторах. Точный список доступных методов платежа зависит от Вашего географического положения. Некоторые способы могут работать только в одну сторону: только на пополнение, но не на вывод — или наоборот. Скорость обработки заявок зависит от платежной системы. При пополнении депозита средства обычно поступают на счет мгновенно. Вывод выигрышей может занять от нескольких часов до нескольких суток. Большинство платежных систем взимают комиссии за свои услуги, и букмекер не может повлиять на объем этих выплат. Уточнить размер комиссий можно на сайте либо в службе поддержки платежной системы. Сами букмекерские конторы тоже имеют право взимать комиссии за денежные транзакции — но некоторые платформы отказались от такой практики. У каждого способа оплаты есть минимальные и максимальные лимиты на ввод и вывод средств. Для выведения крупных выигрышей обычно оптимальны криптовалюты — у них либо совсем отсутствуют максимальные лимиты, либо они значительно превышают лимиты прочих платежных систем.',
    sport_import_criteria: '5 важных критериев для рейтинга лучших букмекерских контор',
    sport_import_criteria_li_1: '1. Служба поддержки клиентов ',
    sport_import_criteria_li_1_t:
      'Важно, чтобы поддержка букмекера общалась на русском или другом языке, котором Вы владеете свободно. В большинство браузеров сегодня встроены автоматические переводчики — но им не стоит доверять на 100%, так как они не всегда справляются со специфической терминологией беттинга. Поддержка должна быть доступна круглосуточно и по нескольким каналам: лайв-чат, телефон, электронная почта, мессенджеры. Дополнительным способом связи с БК являются официальные аккаунты проекта в соцсетях. Качество работы службы поддержки является важным показателем качества работы конторы в целом. Опытные беттеры еще до создания аккаунта в новом БК задают вопросы сотрудникам поддержки, чтобы оценить, насколько быстро и компетентно они реагируют.',
    sport_import_criteria_li_2: '2. Безопасность Вашего счёта',
    sport_import_criteria_li_2_t:
      'Все достойные внимания букмекеры предлагают двухфакторную аутентификацию (2FA). Это означает, что ввода логина и пароля недостаточно для входа в аккаунт. Вам на электронную почту или телефон придет дополнительный код, который надо будет ввести на сайте БК. В последние годы на рынке появляются букмекеры, чьи сайты работают на блокчейне. Это сводит к нулю вероятность мошенничества, так как в систему записывается информация обо всех совершенных действиях: от принятия ставок до оглашения результатов матча, от начисления бонуса до выполнения заявки на вывод средств. Удалить это сведения из блокчейна или незаметно переписать их невозможно.',
    sport_import_criteria_li_3: '3. Платежи: Как вывести средства на свои реквизиты?',
    sport_import_criteria_li_3_t:
      'Правила вывода средств зависят не только от букмекера, но и от платежной системы. Почти все системы берут комиссии за проведение финансовых транзакций, поэтому Вы должны сами заранее уточнить, какой процент с Вас будут взимать. Выгоднее ориентироваться на таких букмекеров, которые не добавляют к этим отчислениям дополнительных комиссий со своей стороны.',
    sport_import_criteria_li_4: '4. Лицензия',
    sport_import_criteria_li_4_t:
      'Наличие лицензии является основополагающим критерием при выборе букмекера. Наличие у БК этого документа является гарантией того, что: Ваши персональные сведения будут храниться строго конфиденциально. Никакие третьи лица ни при каких обстоятельствах не получат к ним доступ. Вознаграждения будут выплачиваться быстро и честно. Букмекер не станет жульничать, менять коэффициенты или применять скрытые комиссии. Номер лицензии и название выдавшей ее организации обычно размещаются либо в футере на главной странице, либо в разделе “О нас”. Если Вы не видите этой информации на сайте, обратитесь в техподдержку. Потом зайдите на сайт той организации, что выдала букмекеру лицензию, и убедитесь, что контора действительно там упоминается.',
    sport_import_criteria_li_5: '5. Бонусы',
    sport_import_criteria_li_5_t:
      'Тут же надо отметить, что при выборе букмекера не стоит ориентироваться на количество и разнообразие бонусов. Главное во всех поощрительных акциях — то, насколько они целесообразны. Посчитайте заранее, превысит ли полученная от бонуса выгода те затраты, которые придется понести ради его получения? Устраивает ли Вас вейджер? Уложитесь ли Вы во время, отведенное на использование бонуса? Контора будет пытаться воздействовать на Ваши эмоции — но Вы должны мыслить прагматично.',
  },

  [LOCALES.UKRAINIAN]: {
    nav_casino: 'Топ онлайн казино',
    nav_sport: 'Топ ставки на спорт',
    nav_faq: 'F.A.Q.',
    title_casino: 'Топ онлайн казино у 2023 році',
    title_sport: 'Топ ставки на спорт',
    description_casino:
      'ТОП онлайн-казино. ТОП онлайн ставки на спорт. Грай тільки в ліцензованих казино. Всі наші казино та ставки на спорт 100% безпечні та перевірені часом. При реєстрації ви отримаєте топові бонуси. Найкращі кешбеки до 10%. Завжди актуальні посилання. Швидкі виплати. Завжди готові допомогти вам в нашому телеграм каналі. Всі наші казино на перший депозит від 100% + FS. При реєстрації додатково за нашим промкодом ви отримаєте додатковий бонус.',
    description_sport:
      'ТОП онлайн ставки на спорт. Всі наші партнери 100% безпечні та перевірені часом. Високі коефіцієнти. Найкращі букмекерські контори. Завжди актуальні бонуси та посилання. Завжди готові допомогти вам в нашому телеграм каналі.',
    link_bonus: 'Забрати бонус',
    footer_text:
      "Інформаційний ресурс Win to time не проводить ігри на реальні та/або віртуальні гроші, також сайт не приймає в жодній формі оплату ставок та/інших платежів, які пов'язані/можуть бути пов'язані з азартними іграми, букмекерами чи тоталізаторами. Будь-які матеріали на інформаційному ресурсі Win to time публікуються виключно з інформаційною метою. Участь в азартних іграх може викликати ігрову залежність. Дотримуйтесь правил (принципів) відповідальної гри. При появі перших ознак залежності негайно зверніться до фахівця. Пам'ятайте, що участь в азартних іграх не може бути джерелом доходів чи альтернативою роботі.",
    contacts: 'Наші контакти:',
    telegram_title: 'Наш Телеграм',
    facebook_title: 'Наш Facebook',
    instagram_title: 'Наш Instagram',
    mail_title: 'Наша пошта',
    page_not_found: 'Сторінку не знайдено',
    content_faq: 'Зміст',
    content_li_1: 'Найкращі онлайн-казино',
    content_li_2: 'Які способи оплати пропонують найкращі онлайн казино',
    content_li_3: '7 важливих критеріїв для рейтингу найкращих онлайн казино',
    best_cas:
      "З того часу, як гральна діяльність у багатьох країнах світу була перенесена у виділені зони, повністю або частково заборонена, індустрія онлайн-гемблінгу стала активно розвиватися. В інтернет-казино з'явилися мільйони шанувальників. Але навіть досвідчені гравці далеко не завжди добре орієнтуються у виборі віртуального закладу, сотні яких відкрили за останні 10-15 років. Чим більше сайт надає можливості для поповнення рахунку, тим краще. Адже фінансова частина питання в азартних іграх за гроші має першорядне значення. Безкоштовна гра - найкращий спосіб «вивчити» роботу ігрового автомата, що сподобався, або настільної гри. Без оплати неможливо грати лише в карткові ігри, деякі лотереї та рулетку з живими дилерами.",
    pay_cas:
      'Зазвичай букмекери пропонують на вибір такі способи поповнення рахунку та виведення виграних коштів:',
    pay_cas_li_1: 'банківські картки;',
    pay_cas_li_2: 'електронні гаманці;',
    pay_cas_li_3: 'криптовалютні гаманці;',
    pay_cas_li_4: 'платіжні термінали;',
    pay_cas_li_5: 'рахунки мобільних операторів.',
    pay_text:
      'Перші два способи є основними і є практично у всіх конторах. Точний перелік доступних методів платежу залежить від Вашого географічного положення. Деякі способи можуть працювати тільки в один бік: тільки на поповнення, але не на висновок чи навпаки. Швидкість обробки заявок залежить від платіжної системи. При поповненні депозиту кошти зазвичай надходять на рахунок миттєво. Виведення виграшів може зайняти від кількох годин до кількох діб. Більшість платіжних систем стягують комісії за свої послуги і букмекер не може вплинути на обсяг цих виплат. Уточнити розмір комісій можна на сайті або службі підтримки платіжної системи. Самі букмекерські контори теж мають право стягувати комісії за грошові транзакції, але деякі платформи відмовилися від такої практики. Кожен спосіб оплати має мінімальні та максимальні ліміти на введення та виведення коштів. Для виведення великих виграшів зазвичай оптимальні криптовалюти - вони або зовсім відсутні максимальні ліміти, або вони значно перевищують ліміти інших платіжних систем.',
    rait_cas_li_1: '1. Як вибрати чесне онлайн казино',
    rait_cas_li_1_t:
      'Ми виділили вам важливі критерії, які неодмінно слід враховувати у своєму виборі віртуального казино для гри на гроші. Облік перелічених факторів – ваш реальний захист від шахраїв у гемблінг-індустрії.',
    rait_cas_li_2: '2. Ліцензія казино',
    rait_cas_li_2_t:
      "Ніякі бонусні програми та вигідні акції не мають значення, коли користувач надходить до казино, у якого відсутня ліцензія. Тільки цей документ дозволяє провадити ігрову діяльність. Здійснюється ліцензування гральним регулятором чи безпосередньо урядом країни, в юрисдикції якої зареєстровано заклад. Перевірені оператори зі світовим ім'ям проходять таку процедуру на островах Мен, Кюрасао, Олдерні та деяких інших можуть мати дозвіл, виданий регуляторами на Мальті або у Великобританії. Ліцензованому закладу не потрібно приховувати інформацію про ліцензування. Номер документа та інші дані зазвичай вказуються безпосередньо на сайтах у нижній частині сторінки. Щоб перевірити справжність інформації, достатньо зайти на веб-ресурс органу, що ліцензує, і перевірити актуальність ліцензії за номером. Для гравця наявність ліцензії – це юридичний захист. Якщо з якихось причин у вас виникне конфлікт із закладом (вам відмовлять у виплаті великого виграшу, наприклад, без реальних на те підстав), ви зможете звернутися до органів, які здійснюють нагляд за азартною діяльністю. І вашу ситуацію буде розглянуто незалежними арбітрами протягом 3 тижнів. Немає ліцензії – немає гарантій чесних виплат, ні захисту. Ваш обліковий запис зможуть безпідставно заблокувати, і на цьому ігрова історія закінчиться, а гроші нечесний оператор просто привласнить собі. Неліцензовані заклади нерідко «грішать» використанням підкручених несертифікованих слотів можуть підтасувати результати турніру і не тільки. Змусити його згодом справедливо виплатити гроші практично неможливо – немає достатнього юридичного інструменту для успішного ведення справи. Доступність Переконайтеся, що онлайн-казино приймає гравців із вашої країни. Список заборонених країн зазвичай є на сайті. Якщо гемблерів-резидентів із вашої країни заклад не приймає, у вас можуть згодом виникнути труднощі з проходженням верифікації та виведенням виграшів.",
    rait_cas_li_3: '3. Служба підтримки клієнтів',
    rait_cas_li_3_t:
      "У будь-якого середньостатистичного гравця час від часу виникає потреба у спілкуванні з представниками служби підтримки для вирішення тієї чи іншої проблеми. Перевірте заздалегідь, що у вашому закладі немає проблем з отриманням зворотного зв'язку. Перед реєстрацією переконайтеся, що на сайті є онлайн-чат, де оператори дійсно відповідають мовою вашого повсякденного спілкування. Ідеальний варіант – наявність кількох варіантів контактів. Нехай це буде не тільки живий чат, а й адреса електронної пошти, номер телефону або скайп-чат. Заздалегідь уточніть, чи працює техпідтримка цілодобово або відповідає клієнтам тільки в денний час. В останньому випадку, якщо ви гратимете вночі, жодну проблему вирішити оперативно просто не вийде.",
    rait_cas_li_4: '4. Варіанти введення та виведення коштів',
    rait_cas_li_4_t:
      "Чим більше сайт надає можливості для поповнення рахунку, тим краще. Адже фінансова частина питання в азартних іграх за гроші має першорядне значення. Переконайтеся, що у казино передбачені способи виведення, які вам підходять: банківські картки, електронні гаманці, всілякі платіжні системи. Заздалегідь уточніть: наскільки швидко надходять кошти на рахунок, і чи немає комісії за введення грошей; чи вимагає казино обов'язково відіграти власний депозит хоча б один раз (адекватні заклади таких вимог до своїх клієнтів не пред'являють); у якій валюті можна поповнювати рахунок та грати; наскільки швидко обробляються заявки на висновок, чи немає додаткових обмежень щодо виплати власних коштів гравцям, які, наприклад, беруть участь у бонусній програмі; чи є ліміти (максимальні та мінімальні) на виведення коштів на добу, тиждень, місяць тощо. Вас має насторожити заявлений адміністрацією факт надмірно довгої обробки заявок. Наприклад, якщо у правилах прописано, що гроші виводяться протягом 5-7 діб – це довго. Якщо заклад залишає за собою право виплачувати великі виграші частинами, також не варто зв'язуватися з ним. Якщо заявки обробляються протягом доби – все чудово!",
    rait_cas_li_5: '5. Як репутація впливає вибір інтернет-казино?',
    rait_cas_li_5_t:
      'У сучасному світі, де доступ до будь-якої інформації є максимально доступним, репутація відіграє чи не першорядну роль. Це той чинник, який не може вплинути недобросовісний гральний заклад. Можна заманювати нових гравців сотнями бонусних програм із неймовірною щедрістю, але якщо в мережі бренд «роздавлений» сотнями негативних відгуків та скарг, з цим боротися не вдасться. Репутаційна оцінка набагато важливіша за рекламу. Вивчення відгуків та інших рейтингових оцінок – найкращий спосіб знайти відповідального та надійного оператора. Незалежні рейтинги мало враховують дані, які публікують самі гральні клуби. Сторонні інтернет-огляди допомагають формувати громадську думку. І на нього точно варто спиратися на гемблера.',
    rait_cas_li_6: '6. Чи можна заробити на інтернет-казино?',
    rait_cas_li_6_t:
      "Не слід сприймати казино як місце роботи. У класичному розумінні заробіток тут здобути неможливо: ніхто не дасть гарантії, що, постійно граючи, людина може розраховувати на стабільний дохід. Звичайно, якщо ви не професійний гравець у покер. Там справа інакша: грамотні стратегії дозволяють досвідченим гравцям вигравати із завидною сталістю. Обивателю слід усвідомити, що ніякі тактики і стратегії – не 100% гарантія виграшу. Щоправда, є кілька рекомендацій, які хоч і не дозволять стати доларовими мільйонерами, але допоможуть не бездумно робити ставки в першому слоті: Шукайте для гри тільки перевірені, чесні гральні заклади з хорошим рейтингом і чистою репутацією. Вибирайте у списку слотів ті, де є можливість отримання більш-менш великих виграшів. Така інформація обов'язково знайдеться на сайті у таблиці з виплатами. Не зупиняйтесь на одному казино. Якщо ви занадто часто виграватимете, служба підтримки неодмінно зверне на вас увагу. Все ж таки гральні клуби працюють не для того, щоб вас «озолотити» – вони зацікавлені заробляти самі. Використовуйте бонусні пропозиції. Але лише тими, де діють адекватні умови відіграшу. Середній вейджер не повинен становити понад х30 – х35. Якщо програли, не намагайтеся відразу «повернути» втрачене. Не можна грати на емоціях – лише з «холодною» головою. Звертайте увагу на найпопулярніші слоти. До цієї категорії потрапляють автомати, в які грали найчастіше. Чим більше слот «заряджений» грошима інших гравців, тим вища ймовірність віддачі великого виграшу.",
    rait_cas_li_7: '7. Чи можна обіграти казино і як це зробити',
    rait_cas_li_7_t:
      "Слід розуміти роботу теорії ймовірності. Кожен слот має свій показник «віддачі». У перевірених провайдерів ця цифра становить близько 93-97%. Що це означає? 93% вкладених в автомат грошей повертається гравцям як виграші. Сума, що залишилася, - чистий дохід грального закладу. Запам'ятайте кілька критеріїв: Якщо попередні користувачі програли достатньо коштів, ймовірність отримання виграшу значно збільшується. Чим більше коштів ви вкладаєте в гру, тим вищий шанс вийти переможцем. Неможливо зірвати великий куш, граючи за мінімальною ставкою. Грати краще на перевірених слотах із високим відсотком видачі. Нема рації сідати за автомат, у якого цей показник становить 70-75%. Нові слоти нерідко дають змогу перемогти. Так провайдери софту привертають увагу відвідувачів. Якщо «новинка» з'явилася на сайті буквально днями, пробувати варто. Важливо розуміти, що кожна гра у закладі має свої встановлені налаштування та функціонує за певною схемою. Саме розуміння цієї схеми дозволяє грамотним клієнтам забирати великі виграші. Але, звичайно, слід міняти казино час від часу, щоб вами не зацікавилися в СП і не урізали можливості ставок.",
    sport_li_1: 'Найкращий букмекер для розміщення ставок в Інтернеті',
    sport_li_2: 'Які способи оплати пропонують найкращі букмекери?',
    sport_li_3: '5 важливих критеріїв для рейтингу найкращих букмекерських контор',
    the_best_online: 'Найкращий букмекер для розміщення ставок в Інтернеті',
    the_best_online_t:
      "Онлайн-беттінг з кожним роком стає все популярнішим. Власники практично будь-яких моделей комп'ютерів, смартфонів чи планшетів можуть зареєструватися на сайті букмекерської контори та почати робити ставки. Для цього достатньо бути повнолітнім і мати стабільне підключення до інтернету. Багато букмекерів пропонують широкий вибір спортивних ставок. Однак це не означає, що всі провайдери однаково підходять для розміщення спортивних ставок. Тому ми представляємо огляди провайдерів, які заробили довіру своїх клієнтів упродовж багатьох років. Амбітні новачки зможуть знайти свого букмекера у нашому списку. Можна сказати одне: кожен провайдер для того, щоб потрапити в категорію «Букмекерська контора місяця», повинен відповідати високим стандартам якості. Іншими словами: цим букмекерам можна довіряти!",
    sport_pay: 'Які способи оплати пропонують найкращі букмекери?',
    sport_pay_t:
      'Зазвичай букмекери пропонують на вибір такі способи поповнення рахунку та виведення виграних коштів:',
    sport_pay_li_1: 'банківські картки;',
    sport_pay_li_2: 'електронні гаманці;',
    sport_pay_li_3: 'криптовалютні гаманці;',
    sport_pay_li_4: 'платіжні термінали;',
    sport_pay_li_5: 'рахунки мобільних операторів.',
    sport_pay_text:
      'Перші два способи є основними і є практично у всіх конторах. Точний перелік доступних методів платежу залежить від Вашого географічного положення. Деякі способи можуть працювати тільки в один бік: тільки на поповнення, але не на висновок чи навпаки. Швидкість обробки заявок залежить від платіжної системи. При поповненні депозиту кошти зазвичай надходять на рахунок миттєво. Виведення виграшів може зайняти від кількох годин до кількох діб. Більшість платіжних систем стягують комісії за свої послуги і букмекер не може вплинути на обсяг цих виплат. Уточнити розмір комісій можна на сайті або службі підтримки платіжної системи. Самі букмекерські контори теж мають право стягувати комісії за грошові транзакції, але деякі платформи відмовилися від такої практики. Кожен спосіб оплати має мінімальні та максимальні ліміти на введення та виведення коштів. Для виведення великих виграшів зазвичай оптимальні криптовалюти - вони або зовсім відсутні максимальні ліміти, або вони значно перевищують ліміти інших платіжних систем.',
    sport_import_criteria: '5 важливих критеріїв для рейтингу найкращих букмекерських контор',
    sport_import_criteria_li_1: '1. Служба підтримки клієнтів',
    sport_import_criteria_li_1_t:
      "Важливо, щоб підтримка букмекера спілкувалася російською чи іншою мовою, якою Ви володієте вільно. У більшість браузерів сьогодні вбудовані автоматичні перекладачі — але їм не варто довіряти на 100%, оскільки вони не завжди впораються зі специфічною беттинговою термінологією. Підтримка має бути доступна цілодобово і кількома каналами: лайв-чат, телефон, електронна пошта, месенджери. Додатковим способом зв'язку з БК є офіційні облікові записи проекту в соцмережах. Якість роботи служби підтримки є важливим показником якості роботи контори загалом. Досвідчені беттери ще до створення облікового запису в новому БК ставлять питання співробітникам підтримки, щоб оцінити, наскільки швидко та компетентно вони реагують.",
    sport_import_criteria_li_2: '2. Безпека Вашого рахунку',
    sport_import_criteria_li_2_t:
      "Всі цікаві букмекери пропонують двофакторну аутентифікацію (2FA). Це означає, що введення логіну та пароля недостатньо для входу в обліковий запис. Вам на електронну пошту чи телефон прийде додатковий код, який потрібно буде запровадити на сайті БК. В останні роки на ринку з'являються букмекери, сайти яких працюють на блокчейні. Це зводить до нуля ймовірність шахрайства, тому що в систему записується інформація про всі скоєні дії: від прийняття ставок до оголошення результатів матчу, від нарахування бонусу до виконання заявки на виведення коштів. Видалити ці відомості з блокчейна або непомітно переписати їх неможливо.",
    sport_import_criteria_li_3: '3. Платежі: Як вивести гроші на свої реквізити?',
    sport_import_criteria_li_3_t:
      'Правила виведення коштів залежить не тільки від букмекера, а й від платіжної системи. Майже всі системи беруть комісії за проведення фінансових транзакцій, тому Ви повинні заздалегідь уточнити, який відсоток з Вас стягуватимуть. Найвигідніше орієнтуватися на таких букмекерів, які не додають до цих відрахувань додаткових комісій зі свого боку.',
    sport_import_criteria_li_4: '4. Ліцензія',
    sport_import_criteria_li_4_t:
      'Наявність ліцензії є основним критерієм для вибору букмекера. Наявність у БК цього документа є гарантією того, що: Ваші персональні відомості зберігатимуться суворо конфіденційно. Жодні треті особи за жодних обставин не отримають до них доступу. Винагороди виплачуватимуть швидко та чесно. Букмекер не шахраюватиме, змінюватиме коефіцієнти або застосовуватиме приховані комісії. Номер ліцензії та назва організації, що її видала, зазвичай розміщуються або у футері на головній сторінці, або в розділі “Про нас”. Якщо Ви не бачите цієї інформації на сайті, зверніться до технічної підтримки. Потім зайдіть на сайт тієї організації, що видала букмекеру ліцензію, і переконайтеся, що контора там справді згадується.',
    sport_import_criteria_li_5: '5. Бонуси',
    sport_import_criteria_li_5_t:
      'Тут же слід зазначити, що при виборі букмекера не варто орієнтуватися на кількість та різноманітність бонусів. Головне у всіх заохочувальних акціях — те, наскільки вони є доцільними. Порахуйте заздалегідь, чи перевищить отримана від бонусу вигода ті витрати, які доведеться зазнати заради його отримання? Чи влаштовує Вас вейджер? Чи вкладетеся Ви під час, відведений на використання бонусу? Контора намагатиметься впливати на Ваші емоції, але Ви повинні мислити прагматично.',
  },
};
