export const casino_en = [
  {
    id: '1',
    logo: require('../images/logo/casino/vavada.png'),
    title: 'Vavada',
    rating: 4.98,
    description: 'Welcome bonus up to $1000 + 100 free spins',
    feature: [
      'Licensed Casino',
      'Withdrawal time - up to 24 hours, on average from 15 minutes to 2 hours',
      'Cashback - monthly 10%, accrual on the 1st day of each month races, tournaments',
      'For registration you get an additional bonus of 100 free spins in The Great Pigsby Megaways',
    ],
    link: 'https://partner-vavada.com/?promo=cd1b2825-b6da-41ed-ae77-3ea0d5d7ba0c&target=register',
  },
  {
    id: '2',
    logo: require('../images/logo/casino/starda.png'),
    title: 'STARDA',
    rating: 4.95,
    description: 'Get up to 100% + 500 FS on your first deposit',
    feature: ['Licensed Casino', 'Fast payouts', 'Fast support'],
    link: 'https://strd-irrs01.com/c45dc50c0',
  },
  {
    id: '3',
    logo: require('../images/logo/casino/rox.png'),
    title: 'ROX Casino',
    rating: 4.9,
    description: 'Bonus 150% up to 3,500 ₴ for the first deposit from 400 ₴',
    feature: [
      'Bonus 150% up to 18,000 ₴ for the first deposit from 2,400 ₴',
      'Double gift for the first deposit',
      'Licensed Casino',
      'Fast payouts',
      'Fast support',
      'SPORTBONUS 150% on the first deposit',
    ],
    link: 'https://rox-fwuocypyjf.com/cbdf43888',
  },
  {
    id: '4',
    logo: require('../images/logo/casino/volna.png'),
    title: 'VOLNA Casino',
    rating: 4.78,
    description: 'Get up to 100% + free spins on your first deposit',
    feature: [
      'Get up to 75% + free spins on your second and third deposits.',
      'Licensed Casino',
      'Fast payouts',
      'Cashback up to 10% every week',
      'Fast support',
    ],
    link: 'https://vln-irrs01.com/c37ec95d6',
  },
  {
    id: '5',
    logo: require('../images/logo/casino/legzo.png'),
    title: 'LEGZO',
    rating: 4.8,
    description: 'Get up to 100% + up to 500 free spins on your first deposit',
    feature: [
      'Cashback up to 10% every Wednesday',
      'Licensed Casino',
      'Fast payouts up to 4 hours',
      'Fast support',
    ],
    link: 'https://gzo-irrs01.com/cf17ad0ff',
  },
  {
    id: '6',
    logo: require('../images/logo/casino/1win.png'),
    title: '1WIN',
    rating: 4.65,
    description: 'Deposit Bonus +500% - Offer available to new 1win customers only',
    feature: [
      'Licensed Casino',
      '1win coins is a gratitude to our loyal customers',
      'Play with us and get 1win coins as a reward',
      'Weekly cashback up to 30% at the casino',
    ],
    link: 'https://1wxmgz.top/casino/list?open=register',
  },
  {
    id: '7',
    logo: require('../images/logo/casino/ttrcasino.png'),
    title: 'TTR casino',
    rating: 4.75,
    description: 'Slot race €10000 weekly tournament',
    feature: ['Licensed Casino', 'Fast payouts', '100% for the first deposit', '50% Reload bonus'],
    link: 'https://regttr.casa/adb35b006',
  },
  {
    id: '8',
    logo: require('../images/logo/casino/dlx.png'),
    title: 'DLX casino',
    rating: 4.72,
    description: 'Exclusive VIP program',
    feature: [
      'Licensed Casino',
      'Fast payouts',
      '100% for the first deposit',
      'After verifying your account, you can get 100 free spins in Buffalo Hunter',
    ],
    link: 'https://regdlx.casa/a134ba7f7',
  },
  {
    id: '9',
    logo: require('../images/logo/casino/ltc.png'),
    title: 'LTC casino',
    rating: 4.7,
    description: 'Licensed CRYPTO CASINO',
    feature: ['Fast payouts', '100% safe', 'Support service'],
    link: 'https://regltc.casa/a890dc58d',
  },
  {
    id: '10',
    logo: require('../images/logo/casino/slotum.png'),
    title: 'SLOTUM',
    rating: 4.87,
    description: 'Get up to 100% up to 250€ + 100FS',
    feature: [
      'Licensed Casino',
      'Fast payouts',
      'Second deposit bonus 50% up to 200€',
      'Third deposit bonus 200% up to 100€ +50FS',
      'Reload bonus 50% up to 100€ + 100FS',
    ],
    link: 'https://slotum.team/a8afd8ff6',
  },
  {
    id: '11',
    logo: require('../images/logo/casino/combo.png'),
    title: 'COMBO SLOTS',
    rating: 4.85,
    description: 'First deposit bonus 100% up to €200 + 100 free spins',
    feature: [
      'Second deposit bonus 75% up to €100 + 50 free spins',
      'Third deposit bonus 50% up to €100 + 75 free spins',
      'Fourth deposit bonus 100% up to €100 + 50 free spins',
      'Weekend reload bonus 50% up to €100 + 100 free spins upon registration (bonus code: FATALITY)',
      'Licensed Casino',
      'Fast payouts',
    ],
    link: 'https://comboslots.org/a9d9e8770',
  },
];
