export const CasinoList = [
  {
    id: '1',
    logo: require('../images/logo/casino/vavada.png'),
    title: 'Vavada',
    rating: 5,
    description: 'Приветственный бонус до 1000$ + 100 фриспинов',
    feature: [
      'Лицензированное казино',
      'Время вывода - до 24 часов, в среднем от 15 минут до 2 часов',
      'Кэшбэк - ежемесячный 10%, начисление 1 числа каждого месяца Гонки, турниры',
      'За регистрацию вы получаете дополнительно бонус 100 фриспинов в The Great Pigsby Megaways',
    ],
    link: 'https://partner-vavada.com/?promo=cd1b2825-b6da-41ed-ae77-3ea0d5d7ba0c&target=register',
  },
  {
    id: '2',
    logo: require('../images/logo/casino/starda.png'),
    title: 'STARDA',
    rating: 4.9,
    description: 'Получи до 100% + 500 FS на первый депозит',
    feature: ['Лицензированное казино.', 'Быстрые выплаты.', 'Быстрая служба поддержки'],
    link: 'https://strd-irrs01.com/c45dc50c0',
  },
  {
    id: '3',
    logo: require('../images/logo/casino/rox.png'),
    title: 'ROX Casino',
    rating: 4.8,
    description: 'БОНУС 150% ДО 3 500 ₴ ЗА ПЕРВЫЙ ДЕПОЗИТ ОТ 400 ₴',
    feature: [
      'БОНУС 150% ДО 18 000 ₴ ЗА ПЕРВЫЙ ДЕПОЗИТ ОТ 2 400 ₴.',
      'Двойной подарок за первый депозит.',
      'Лицензированное казино.',
      'Быстрые выплаты.',
      'Быстрая служба поддержки.',
      'СПОРТБОНУС 150% на первый депозит.',
    ],
    link: 'https://rox-fwuocypyjf.com/cbdf43888',
  },
  {
    id: '5',
    logo: require('../images/logo/casino/volna.png'),
    title: 'VOLNA Casino',
    rating: 4.5,
    description: 'Получи до 100% + фриспины на первый депозит',
    feature: [
      'Получи до 75% + фриспины на второй и третий депозит.',
      'Лицензированное казино.',
      'Быстрые выплаты.',
      'Кешбек до 10% каждую неделю.',
      'Быстрая служба поддержки',
    ],
    link: 'https://vln-irrs01.com/c37ec95d6',
  },
  {
    id: '7',
    logo: require('../images/logo/casino/legzo.png'),
    title: 'LEGZO',
    rating: 4.7,
    description: 'Получи до 100% + до 500 фриспинов на первый депозит',
    feature: [
      'Кешбек до 10% каждую среду.',
      'Лицензированное казино.',
      'Быстрые выплаты до 4х часов.',
      'Быстрая служба поддержки',
    ],
    link: 'https://gzo-irrs01.com/cf17ad0ff',
  },
  {
    id: '9',
    logo: require('../images/logo/casino/1win.png'),
    title: '1WIN',
    rating: 4,
    description: 'Бонус на депозит +500% - Предложение доступно только для новых клиентов «1win»',
    feature: [
      'Лицензированное казино',
      '1win coins - это благодарность нашим лояльным клиентам.',
      'Играй с нами и получай в награду 1win coins.',
      'Еженедельный кэшбэк до 30% на казино.',
    ],
    link: 'https://1wxmgz.top/casino/list?open=register',
  },
  {
    id: '10',
    logo: require('../images/logo/casino/ttrcasino.png'),
    title: 'TTR casino',
    rating: 4.5,
    description: 'Слото гонка €10000 еженедельный турнир',
    feature: [
      'Лицензированное казино',
      'Быстрые выплаты.',
      '100% за первый депозит.',
      '50% Reload-бонус.',
    ],
    link: 'https://regttr.casa/adb35b006',
  },
  {
    id: '11',
    logo: require('../images/logo/casino/dlx.png'),
    title: 'DLX casino',
    rating: 4.5,
    description: 'Эксклюзивная VIP программа',
    feature: [
      'Лицензированное казино',
      'Быстрые выплаты.',
      '100% за первый депозит.',
      'После верификации акаунта можете получить 100 фриспинов в Buffalo Hunter.',
    ],
    link: 'https://regdlx.casa/a134ba7f7',
  },
  {
    id: '12',
    logo: require('../images/logo/casino/ltc.png'),
    title: 'LTC casino',
    rating: 4.5,
    description: 'Лицензированное КРИПТО КАЗИНО',
    feature: ['Быстрые выплаты.', '100% безопасно.', 'Служба поддержки.'],
    link: 'https://regltc.casa/a890dc58d',
  },
];
