export const casino_ukr = [
  {
    id: '1',
    logo: require('../images/logo/casino/vavada.png'),
    title: 'Vavada',
    rating: 4.98,
    description: 'Вітальний бонус до 1000 $ + 100 фриспінів',
    feature: [
      'Ліцензоване казино',
      'Час виведення – до 24 годин, в середньому від 15 хвилин до 2 годин',
      'Кешбек - щомісячний 10%, нарахування 1 числа кожного місяця Гонки, турніри',
      'За реєстрацію ви отримуєте додатково бонус 100 фриспінів у The Great Pigsby Megaways',
    ],
    link: 'https://partner-vavada.com/?promo=cd1b2825-b6da-41ed-ae77-3ea0d5d7ba0c&target=register',
  },
  {
    id: '2',
    logo: require('../images/logo/casino/starda.png'),
    title: 'STARDA',
    rating: 4.95,
    description: 'Отримай до 100% + 500 FS на перший депозит',
    feature: ['Ліцензоване казино', 'Швидкі виплати', 'Швидка служба підтримки'],
    link: 'https://strd-irrs01.com/c45dc50c0',
  },
  {
    id: '3',
    logo: require('../images/logo/casino/rox.png'),
    title: 'ROX Casino',
    rating: 4.9,
    description: 'Бонус 150% до 3 500 ₴ за перший депозит від 400 ₴',
    feature: [
      'Бонус 150% до 18 000 ₴ за перший депозит від 2 400 ₴',
      'Подвійний подарунок за перший депозит',
      'Ліцензоване казино',
      'Швидкі виплати',
      'Швидка служба підтримки',
      'СПОРТБОНУС 150% на перший депозит',
    ],
    link: 'https://rox-fwuocypyjf.com/cbdf43888',
  },
  {
    id: '4',
    logo: require('../images/logo/casino/volna.png'),
    title: 'VOLNA Casino',
    rating: 4.78,
    description: 'Отримай до 100% + фриспіни на перший депозит',
    feature: [
      'Отримай до 75% + фриспіни на другий та третій депозит',
      'Ліцензоване казино',
      'Швидкі виплати',
      'Кешбек до 10% щотижня',
      'Швидка служба підтримки',
    ],
    link: 'https://vln-irrs01.com/c37ec95d6',
  },
  {
    id: '5',
    logo: require('../images/logo/casino/legzo.png'),
    title: 'LEGZO',
    rating: 4.8,
    description: 'Отримай до 100% + до 500 фриспінів на перший депозит',
    feature: [
      'Кешбек до 10% щосереди',
      'Ліцензоване казино',
      'Швидкі виплати до 4х годин',
      'Швидка служба підтримки',
    ],
    link: 'https://gzo-irrs01.com/cf17ad0ff',
  },
  {
    id: '6',
    logo: require('../images/logo/casino/1win.png'),
    title: '1WIN',
    rating: 4.65,
    description: 'Бонус на депозит +500% - Пропозиція доступна тільки для нових клієнтів «1win»',
    feature: [
      'Ліцензоване казино',
      '1win coins - це подяка нашим лояльним клієнтам',
      'Грай з нами та отримуй у нагороду 1win coins',
      'Щотижневий кешбек до 30% на казино',
    ],
    link: 'https://1wxmgz.top/casino/list?open=register',
  },
  {
    id: '7',
    logo: require('../images/logo/casino/ttrcasino.png'),
    title: 'TTR casino',
    rating: 4.75,
    description: 'Слото гонка €10000 щотижневий турнір',
    feature: ['Ліцензоване казино', 'Швидкі виплати', '100% за перший депозит', '50% Reload-бонус'],
    link: 'https://regttr.casa/adb35b006',
  },
  {
    id: '8',
    logo: require('../images/logo/casino/dlx.png'),
    title: 'DLX casino',
    rating: 4.72,
    description: 'Ексклюзивна VIP програма',
    feature: [
      'Ліцензоване казино',
      'Швидкі виплати',
      '100% за перший депозит',
      'Після верифікації акаунту можете отримати 100 фриспінів у Buffalo Hunter',
    ],
    link: 'https://regdlx.casa/a134ba7f7',
  },
  {
    id: '9',
    logo: require('../images/logo/casino/ltc.png'),
    title: 'LTC casino',
    rating: 4.7,
    description: 'Ліцензоване КРИПТО КАЗИНО',
    feature: ['Швидкі виплати', '100% безпечно', 'Служба підтримки'],
    link: 'https://regltc.casa/a890dc58d',
  },
  {
    id: '10',
    logo: require('../images/logo/casino/slotum.png'),
    title: 'SLOTUM',
    rating: 4.87,
    description: 'Отримай до 100% до 250€ + 100FS',
    feature: [
      'Ліцензоване казино',
      'Швидкі виплати',
      'Бонус на другий депозит 50% до 200 €',
      'Бонус на третій депозит 200% до 100€ +50FS',
      'Релоуд-бонус 50% до 100€ + 100FS',
    ],
    link: 'https://slotum.team/a8afd8ff6',
  },
  {
    id: '11',
    logo: require('../images/logo/casino/combo.png'),
    title: 'COMBO SLOTS',
    rating: 4.85,
    description: 'Бонус на перший депозит 100% до € 200 + 100 фриспінів',
    feature: [
      'Бонус на другий депозит 75% до € 100 + 50 фриспінів',
      'Бонус на третій депозит 50% до € 100 + 75 фриспінів',
      'Бонус на четвертий депозит 100% до € 100 + 50 фриспінів',
      'Релоад бонус на вихідні 50% до € 100 + 100 фрі спинів під час реєстрації (бонус код: FATALITY)',
      'Ліцензоване казино',
      'Швидкі виплати',
    ],
    link: '/',
  },
];
