export const sport_ukr = [
  {
    id: '1',
    logo: require('../images/logo/sport/1win.png'),
    title: '1WIN',
    rating: 4.8,
    description: 'Бонус на депозит +500% - Пропозиція доступна тільки для нових клієнтів «1win»',
    feature: [
      'Високі коефіцієнти',
      '1win coins - це подяка нашим лояльним клієнтам',
      'Грай з нами та отримуй у нагороду 1win coins',
      'Бонус на експрес - при здійсненні експресу з 5 і більше подіями до чистого прибутку нараховується відсоток суми виграшу',
    ],
    link: 'https://1wuwsl.top/v2/landing-page/cyber',
  },
  {
    id: '2',
    logo: require('../images/logo/sport/melbet.png'),
    title: 'MELBET',
    rating: 4.75,
    description: 'Бонус на перший депозит 100%',
    feature: [
      'Надійність',
      'Високі коефіцієнти',
      'За реєстрацію ви отримуєте додатково бонус – щотижня бонус 50% до €100 + 30 FS',
    ],
    link: 'https://refpa57118.top/L?tag=s_1968667m_1107c_&site=1968667&ad=1107',
  },
  {
    id: '3',
    logo: require('../images/logo/sport/favbet.png'),
    title: 'FAVORIT',
    rating: 4.95,
    description: 'Бонус 4500₴',
    feature: [
      'На перший депозит 4000грн та ставка без ризику до 500грн',
      'Високі коефіцієнти',
      'Швидкі виплати',
    ],
    link: 'https://analyticsq2.com/fav_uni/?serial=6474&creative_id=20&anid=',
  },
  {
    id: '4',
    logo: require('../images/logo/sport/pm.png'),
    title: 'ПАРИМАТЧ',
    rating: 4.9,
    description: 'Бонус 2500₴',
    feature: [
      'Високі коефіцієнти',
      'Швидкі виплати',
      'За реєстрацію на FreeBet 300 грн на будь-який вид спорту',
    ],
    link: 'https://pmaff.com/?serial=61288438&creative_id=1814&anid=',
  },
  {
    id: '5',
    logo: require('../images/logo/sport/1xbet.png'),
    title: '1XBET',
    rating: 4.7,
    description: 'Реєструйся та отримай 100%-й бонус на суму до 3000 UAH',
    feature: [
      'Високі коефіцієнти',
      'HYPER BONUS - Вигравайте та отримуйте гарантований бонус до 250%!',
      'При поповненні рахунку через платіжну систему MoneyGo отримай бонус 30% кешбек',
      'СТАВКА БЕЗ РИЗИКУ - Отримай Фрібет у разі невдачі',
    ],
    link: 'https://refpa53115.top/L?tag=s_1968173m_355c_&site=1968173&ad=355',
  },
];
