export const sport_en = [
  {
    id: '1',
    logo: require('../images/logo/sport/1win.png'),
    title: '1WIN',
    rating: 4.8,
    description: 'Deposit Bonus +500% - Offer available to new 1win customers only',
    feature: [
      'High odds',
      '1win coins is a gratitude to our loyal customers',
      'Play with us and get 1win coins as a reward',
      'Express bonus - when making an express with 5 or more events, a percentage of the winning amount is added to the net profit',
    ],
    link: 'https://1wuwsl.top/v2/landing-page/cyber',
  },
  {
    id: '2',
    logo: require('../images/logo/sport/melbet.png'),
    title: 'MELBET',
    rating: 4.75,
    description: 'First deposit bonus 100%',
    feature: [
      'Reliability',
      'High odds',
      'For registration you get an additional bonus - every week a 50% bonus up to €100 + 30 FS',
    ],
    link: 'https://refpa57118.top/L?tag=s_1968667m_1107c_&site=1968667&ad=1107',
  },
  {
    id: '3',
    logo: require('../images/logo/sport/favbet.png'),
    title: 'FAVORIT',
    rating: 4.95,
    description: 'Bonus 4500₴',
    feature: [
      'On the first deposit 4000 UAH and risk-free bet up to 500 UAH',
      'High odds',
      'Fast payouts',
    ],
    link: 'https://analyticsq2.com/fav_uni/?serial=6474&creative_id=20&anid=',
  },
  {
    id: '4',
    logo: require('../images/logo/sport/pm.png'),
    title: 'PARIMATCH',
    rating: 4.9,
    description: 'Bonus 2500₴',
    feature: ['High odds', 'Fast payouts', 'For registration, get FreeBet 300 UAH for any sport'],
    link: 'https://pmaff.com/?serial=61288438&creative_id=1814&anid=',
  },
  {
    id: '5',
    logo: require('../images/logo/sport/1xbet.png'),
    title: '1XBET',
    rating: 4.7,
    description: 'Register and get a 100% bonus up to 3000 UAH',
    feature: [
      'High odds',
      'HYPER BONUS - Win and get a guaranteed bonus up to 250%!',
      'When replenishing your account through the MoneyGo payment system, get a 30% cashback bonus',
      'RISK FREE BET - Get a Free Bet if you fail',
    ],
    link: 'https://refpa53115.top/L?tag=s_1968173m_355c_&site=1968173&ad=355',
  },
];
