export const sport_ru = [
  {
    id: '1',
    logo: require('../images/logo/sport/1win.png'),
    title: '1WIN',
    rating: 4.8,
    description: 'Бонус на депозит +500% - Предложение доступно только для новых клиентов «1win»',
    feature: [
      'Высокие коэффициенты',
      '1win coins - это благодарность нашим лояльным клиентам',
      'Играй с нами и получай в награду 1win coins',
      'Бонус на экспресс - при совершении экспресса с 5 и более событиями к чистой прибыли начисляется процент от суммы выигрыша',
    ],
    link: 'https://1wuwsl.top/v2/landing-page/cyber',
  },
  {
    id: '2',
    logo: require('../images/logo/sport/melbet.png'),
    title: 'MELBET',
    rating: 4.75,
    description: 'Бонус на первый депозит 100%',
    feature: [
      'Надежность',
      'Высокие коэффициенты',
      'За регистрацию вы получаете дополнительно бонус - каждую неделю бонус 50 % до €100 + 30 FS',
    ],
    link: 'https://refpa57118.top/L?tag=s_1968667m_1107c_&site=1968667&ad=1107',
  },
  {
    id: '3',
    logo: require('../images/logo/sport/favbet.png'),
    title: 'FAVORIT',
    rating: 4.95,
    description: 'Бонус 4500₴',
    feature: [
      'На первый депозит 4000грн и ставка без риска до 500грн',
      'Высокие коэффициенты',
      'Быстрые выплаты',
    ],
    link: 'https://analyticsq2.com/fav_uni/?serial=6474&creative_id=20&anid=',
  },
  {
    id: '4',
    logo: require('../images/logo/sport/pm.png'),
    title: 'ПАРИМАТЧ',
    rating: 4.9,
    description: 'Бонус 2500₴',
    feature: [
      'Высокие коэффициенты',
      'Быстрые выплаты',
      'За регестрацию получи FreeBet 300 грн на любой вид спорта',
    ],
    link: 'https://pmaff.com/?serial=61288438&creative_id=1814&anid=',
  },
  {
    id: '5',
    logo: require('../images/logo/sport/1xbet.png'),
    title: '1XBET',
    rating: 4.7,
    description: 'Регистрируйся и получи 100%-й бонус на сумму до 3000 UAH',
    feature: [
      'Высокие коэффициенты',
      'HYPER BONUS - Выигрывайте и получайте гарантированный бонус до 250%!',
      'При пополнении счета через платежную систему MoneyGo получи бонус 30% кешбек',
      'СТАВКА БЕЗ РИСКА - Получи Фрибет в случае неудачи',
    ],
    link: 'https://refpa53115.top/L?tag=s_1968173m_355c_&site=1968173&ad=355',
  },
];
