export const SportList_ru = [
  {
    id: '1',
    logo: require('../images/logo/sport/1win.png'),
    title: '1WIN',
    rating: 4.8,
    description: 'Бонус на депозит +500% - Предложение доступно только для новых клиентов «1win»',
    feature: [
      'Высокие коэффициенты',
      '1win coins - это благодарность нашим лояльным клиентам',
      'Играй с нами и получай в награду 1win coins',
      'Бонус на экспресс - при совершении экспресса с 5 и более событиями к чистой прибыли начисляется процент от суммы выигрыша',
    ],
    link: 'https://1wuwsl.top/v2/landing-page/cyber',
  },
  {
    id: '2',
    logo: require('../images/logo/sport/melbet.png'),
    title: 'MELBET',
    rating: 4.75,
    description: 'Бонус на первый депозит 100%',
    feature: [
      'Надежность',
      'Высокие коэффициенты',
      'За регистрацию вы получаете дополнительно бонус - каждую неделю бонус 50 % до €100 + 30 FS',
    ],
    link: 'https://refpa57118.top/L?tag=s_1968667m_1107c_&site=1968667&ad=1107',
  },
  {
    id: '3',
    logo: require('../images/logo/sport/favbet.png'),
    title: 'FAVORIT',
    rating: 4.95,
    description: 'Бонус 4500₴',
    feature: [
      'На первый депозит 4000грн и ставка без риска до 500грн',
      'Высокие коэффициенты',
      'Быстрые выплаты',
    ],
    link: 'https://analyticsq2.com/fav_uni/?serial=6474&creative_id=20&anid=',
  },
  {
    id: '4',
    logo: require('../images/logo/sport/pm.png'),
    title: 'ПАРИМАТЧ',
    rating: 4.9,
    description: 'Бонус 2500₴',
    feature: [
      'Высокие коэффициенты',
      'Быстрые выплаты',
      'За регестрацию получи FreeBet 300 грн на любой вид спорта',
    ],
    link: 'https://pmaff.com/?serial=61288438&creative_id=1814&anid=',
  },
  {
    id: '5',
    logo: require('../images/logo/sport/1xbet.png'),
    title: '1XBET',
    rating: 4.7,
    description: 'Регистрируйся и получи 100%-й бонус на сумму до 3000 UAH',
    feature: [
      'Высокие коэффициенты',
      'HYPER BONUS - Выигрывайте и получайте гарантированный бонус до 250%!',
      'При пополнении счета через платежную систему MoneyGo получи бонус 30% кешбек',
      'СТАВКА БЕЗ РИСКА - Получи Фрибет в случае неудачи',
    ],
    link: 'https://refpa53115.top/L?tag=s_1968173m_355c_&site=1968173&ad=355',
  },
];

export const SportList_ukr = [
  {
    id: '1',
    logo: require('../images/logo/sport/1win.png'),
    title: '1WIN',
    rating: 4.8,
    description: 'Бонус на депозит +500% - Пропозиція доступна тільки для нових клієнтів «1win»',
    feature: [
      'Високі коефіцієнти',
      '1win coins - це подяка нашим лояльним клієнтам',
      'Грай з нами та отримуй у нагороду 1win coins',
      'Бонус на експрес - при здійсненні експресу з 5 і більше подіями до чистого прибутку нараховується відсоток суми виграшу',
    ],
    link: 'https://1wuwsl.top/v2/landing-page/cyber',
  },
  {
    id: '2',
    logo: require('../images/logo/sport/melbet.png'),
    title: 'MELBET',
    rating: 4.75,
    description: 'Бонус на перший депозит 100%',
    feature: [
      'Надійність',
      'Високі коефіцієнти',
      'За реєстрацію ви отримуєте додатково бонус – щотижня бонус 50% до €100 + 30 FS',
    ],
    link: 'https://refpa57118.top/L?tag=s_1968667m_1107c_&site=1968667&ad=1107',
  },
  {
    id: '3',
    logo: require('../images/logo/sport/favbet.png'),
    title: 'FAVORIT',
    rating: 4.95,
    description: 'Бонус 4500₴',
    feature: [
      'На перший депозит 4000грн та ставка без ризику до 500грн',
      'Високі коефіцієнти',
      'Швидкі виплати',
    ],
    link: 'https://analyticsq2.com/fav_uni/?serial=6474&creative_id=20&anid=',
  },
  {
    id: '4',
    logo: require('../images/logo/sport/pm.png'),
    title: 'ПАРИМАТЧ',
    rating: 4.9,
    description: 'Бонус 2500₴',
    feature: [
      'Високі коефіцієнти',
      'Швидкі виплати',
      'За реєстрацію на FreeBet 300 грн на будь-який вид спорту',
    ],
    link: 'https://pmaff.com/?serial=61288438&creative_id=1814&anid=',
  },
  {
    id: '5',
    logo: require('../images/logo/sport/1xbet.png'),
    title: '1XBET',
    rating: 4.7,
    description: 'Реєструйся та отримай 100%-й бонус на суму до 3000 UAH',
    feature: [
      'Високі коефіцієнти',
      'HYPER BONUS - Вигравайте та отримуйте гарантований бонус до 250%!',
      'При поповненні рахунку через платіжну систему MoneyGo отримай бонус 30% кешбек',
      'СТАВКА БЕЗ РИЗИКУ - Отримай Фрібет у разі невдачі',
    ],
    link: 'https://refpa53115.top/L?tag=s_1968173m_355c_&site=1968173&ad=355',
  },
];

export const SportList_en = [
  {
    id: '1',
    logo: require('../images/logo/sport/1win.png'),
    title: '1WIN',
    rating: 4.8,
    description: 'Deposit Bonus +500% - Offer available to new 1win customers only',
    feature: [
      'High odds',
      '1win coins is a gratitude to our loyal customers',
      'Play with us and get 1win coins as a reward',
      'Express bonus - when making an express with 5 or more events, a percentage of the winning amount is added to the net profit',
    ],
    link: 'https://1wuwsl.top/v2/landing-page/cyber',
  },
  {
    id: '2',
    logo: require('../images/logo/sport/melbet.png'),
    title: 'MELBET',
    rating: 4.75,
    description: 'First deposit bonus 100%',
    feature: [
      'Reliability',
      'High odds',
      'For registration you get an additional bonus - every week a 50% bonus up to €100 + 30 FS',
    ],
    link: 'https://refpa57118.top/L?tag=s_1968667m_1107c_&site=1968667&ad=1107',
  },
  {
    id: '3',
    logo: require('../images/logo/sport/favbet.png'),
    title: 'FAVORIT',
    rating: 4.95,
    description: 'Bonus 4500₴',
    feature: [
      'On the first deposit 4000 UAH and risk-free bet up to 500 UAH',
      'High odds',
      'Fast payouts',
    ],
    link: 'https://analyticsq2.com/fav_uni/?serial=6474&creative_id=20&anid=',
  },
  {
    id: '4',
    logo: require('../images/logo/sport/pm.png'),
    title: 'PARIMATCH',
    rating: 4.9,
    description: 'Bonus 2500₴',
    feature: ['High odds', 'Fast payouts', 'For registration, get FreeBet 300 UAH for any sport'],
    link: 'https://pmaff.com/?serial=61288438&creative_id=1814&anid=',
  },
  {
    id: '5',
    logo: require('../images/logo/sport/1xbet.png'),
    title: '1XBET',
    rating: 4.7,
    description: 'Register and get a 100% bonus up to 3000 UAH',
    feature: [
      'High odds',
      'HYPER BONUS - Win and get a guaranteed bonus up to 250%!',
      'When replenishing your account through the MoneyGo payment system, get a 30% cashback bonus',
      'RISK FREE BET - Get a Free Bet if you fail',
    ],
    link: 'https://refpa53115.top/L?tag=s_1968173m_355c_&site=1968173&ad=355',
  },
];
